name: Upload Blender Assets to itch.io

on:
  push:
    #branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Butler
        uses: itch-actions/butler@v1
        with:
          api-key: ${{ secrets.BUTLER_API_KEY }}

      - name: Deploy to itch.io
        run: |
          butler push ./Geometry\ Nodes/ catdev000/geonodes:assets --api-key $BUTLER_API_KEY
